#!/bin/bash
#SBATCH --job-name=MW0 	                   # set job name
#SBATCH --mail-user=michael.petersen@roe.ac.uk # set your mail address
#SBATCH -p GPU
#SBATCH -N 2                      # Number of nodes
#SBATCH --ntasks-per-node=4      # Number of MPI tasks per node
#SBATCH --cpus-per-task=1         # Number of CPU cores per task
#SBATCH --gres=gpu:4              # Number of GPUs per node
#SBATCH --time=71:00:00                        # set max wallclock time
#SBATCH --output=job-%N-%j.out                 # set output log name
#SBATCH --error=job-%N-%j.error                # set error log name %N=first node, %j=job number
#SBATCH --mail-type=ALL                        # set mail alerts

# load modules
module purge
module load cuda hdf5-openmpi

# append a new set of libraries to point at EXP executable:
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/mpetersen/lib:/home/mpetersen/local/lib:/home/mpetersen/lib

# change directory to proper location
cd /disk14/mpetersen/extreme-mwlmc/models/cuillin/LMC

# stamp output with details
pwd; hostname; date

# print the current path to libraries:
echo $LD_LIBRARY_PATH

# set the execution command
export COMMAND="mpirun -v /home/mpetersen/bin/exp run_lmc_model_gpu.yml"

# stamp output with execution command
echo $COMMAND

# run execution command
$COMMAND

# stamp output with end time
date
